base/api/urls.py
from django.urls import path
from . import views

# with prefix 'api/'
urlpatterns = [
    path('', views.getRoutes), # response how to use api
    path('rooms/', views.getRooms),
    path('room/<str:roomID>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginView, name="login"),
    path('logout/', views.logoutView, name="logout"),
    path('register/', views.registerView, name="register"),
    path('activate/<uidb64>/<token>/', views.activateView, name='activate'),
    
    path('', views.home, name="home"),
    path('room/<str:roomID>/', views.room, name="room"),
    path('profile/<str:username>/', views.userProfile, name="profile"),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:roomID>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:roomID>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:msgID>', views.deleteMessage, name="delete-message"),
    path('update-user/', views.updateUser, name="update-user"),
    
    path('topics/', views.topicView, name="topics"),
    path('activity/', views.activityView, name="activity"),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
    
    # __Password__
    # 1. User submits email for reset
    # 2. Email sent message
    # 3. Email with link and reset instructions
    # 4. Password successfully reset message
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='reset-password/reset-password.html'),
         name='reset_password'),
    path('reset-password-sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset-password/reset-password-sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset-password/password-reset-confirm.html'),
         name="password_reset_confirm"),
    path('reset-password-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset-password/password-reset-complete.html'),
         name="password_reset_complete")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
# from django.contrib.auth.models import User

# TODO: Customize User Model
class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True, unique=True)
    bio = models.TextField(null=True)
    status = models.IntegerField(null=False, default=0)
    
    avatar = models.ImageField(null=True, default="avatar.svg")
    
    # when creating superuser, comment out following code
    USERNAME_FIELD = 'email'
    
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=256)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    description = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True) # save timestamp when it is created

    class Meta:
        ordering = ['-updated', '-created'] # in descending order

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True) # save timestamp when it is created
    
    class Meta:
        ordering = ['-updated', '-created'] # in descending order
    
    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from .models import Room, User
from django.contrib.auth.forms import UserCreationForm

# create model form for Room


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        # fields = ['host', 'name'] # customize
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer
from base.api import serializers

@api_view(['GET', 'POST'])
def getRoutes(request):
    routes = [
        'GET /api/rooms',
        'GET /api/rooms/:id',
    ]
    return Response(routes)

@api_view(['GET', 'POST'])
def getRooms(request):
    rooms = Room.objects.all()
    # serialize room objects
    serializer = RoomSerializer(rooms, many=True)
    
    return Response(serializer.data)

@api_view(['GET', 'POST'])
def getRoom(request, roomID):
    room = Room.objects.get(id=roomID)
    # serialize room objects
    serializer = RoomSerializer(room)
    
    return Response(serializer.data)

base/views.py
from django.contrib import auth
from django.http import HttpResponse
from django.http.response import Http404
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Room, Topic, Message, User
from .forms import RoomForm, UserForm, MyUserCreationForm
from .utils import account_activation_token

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage

# Create your views here.

def loginView(request):
    page = 'login'
    
    if (request.user.is_authenticated):
        return redirect('home')
    
    if (request.method == 'POST'):
        email = request.POST.get('email').lower()
        password = request.POST.get('password')
        # check if user exists
        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, "User does not exist")
        # authenticate
        user = authenticate(request, email=email, password=password)
        if (user is not None):
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Username or password incorrect")
    
    context = {
        'page': page,
    }
    
    return render(request, 'base/login_register.html', context)

def logoutView(request):
    logout(request)
    return redirect('home')

def registerView(request):
    page = 'register'
    form = MyUserCreationForm()
    
    if (request.method == 'POST'):
        # delete inactivated user
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if (user is not None) and (user.is_active == False):
            user.delete()
        
        form = MyUserCreationForm(request.POST)
        if (form.is_valid()):
            user = form.save(commit=False)
            
            # require for using uw email to signup
            if (not user.email.endswith('uw.edu')):
                messages.info(request, 'Please signup with UW email.')
                return redirect('register')
            
            user.username = user.username.lower()
            user.is_active = False  # wait for email confirmation
            user.save()
            
            current_site = get_current_site(request)
            subject = 'Activate Your Account @HuskyPlanet'
            message = render_to_string(
                'base/activation/email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                }
            )
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(subject, message, to=[to_email])
            email.send()
            # messages.info(request, 'User account was created but is waiting for activation.')
            return render(request, 'base/activation/activate.html')
            
        else:
            messages.error(request, 'An error occurred during registration')
            return redirect('register')
            
    context = {
        'page': page,
        'form': form,
    }
    
    return render(request, 'base/login_register.html', context)

def activateView(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.first_name = user.username
        user.save()
        login(request, user)
        messages.success(request, 'Welcome back ' + user.username + '!')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        messages.error(request, 'Sorry, we cannot verify your email')
        return HttpResponse('Activation link is invalid!')


def home(request):
    if request.GET.get('q') != None:
        q = request.GET.get('q')
    else:
        q = ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q)
        # | Q(name__icontains=q) # bit operation
    )
    # rooms = Room.objects.filter(topic__name__contains=q)
    # rooms = Room.objects.filter(topic__name__startswith=q)
    topics = Topic.objects.all()
    topics_display = topics[0:5]
    roomCnt = rooms.count()
    room_messages = Message.objects.all().filter(
        Q(room__topic__name__icontains=q)
    )[:5]

    context = {
        'rooms': rooms,
        'topics': topics,
        'topics_display': topics_display,
        'roomCnt': roomCnt,
        'room_messages': room_messages,
    }
    
    # implicit directory basename is base/templates/ in default in Django
    return render(request, 'base/home.html', context) 

def room(request, roomID):
    room = Room.objects.get(id=roomID)
    room_messages = Message.objects.filter(room__name=room)[:5]
    participants = room.participants.all()

    if (request.method == 'POST'):
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('room', roomID=room.id)

    context = {
        'room': room,
        'room_messages': room_messages,
        'participants': participants,
    }

    return render(request, 'base/room.html', context)

def userProfile(request, username):
    user = User.objects.get(username=username)
    rooms = Room.objects.filter(host=user.id)
    room_messages = Message.objects.filter(user=user.id)[:5]
    topics = Topic.objects.all()
    topics_display = topics[0:5]
    
    context = {
        'user': user,
        'rooms': rooms,
        'room_messages': room_messages,
        'topics': topics,
        'topics_display': topics_display,
    }
    
    return render(request, 'base/profile.html', context)


@login_required(login_url='login')
def createRoom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    # for post request
    if (request.method == 'POST'):
        # create topic in database if it doesn't exist
        topic_name = request.POST.get('room_topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        
        # update database for customized form
        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('room_name'),
            description=request.POST.get('description')
        )
        return redirect('home')
    
    context = {
        'form': form,
        'topics': topics,
    }
    
    return render(request, 'base/room_form.html', context)

@login_required(login_url='login')
def updateRoom(request, roomID):
    room = Room.objects.get(id=roomID)
    form = RoomForm(instance=room) # prefill form with room
    topics = Topic.objects.all()
    
    if (request.user != room.host):
        return HttpResponse("No permission")
    
    if (request.method == 'POST'):
        # create topic in database if it doesn't exist
        topic_name = request.POST.get('room_topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('room_name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save() # save update
        return redirect('home')
        
    context = {
        'form': form,
        'topics': topics,
        'room': room,
    }
    
    return render(request, 'base/room_form.html', context)

@login_required(login_url='login')
def deleteRoom(request, roomID):
    room = Room.objects.get(id=roomID)
    if (request.method == 'POST'):
        room.delete()
        return redirect('home')

    context = {
        'obj': room,
    }
    
    return render(request, 'base/delete.html', context)

@login_required(login_url='login')
def deleteMessage(request, msgID):
    message = Message.objects.get(id=msgID)
    
    if (request.user != message.user):
        return HttpResponse('No permission')
    
    if (request.method == 'POST'):
        message.delete()
        return redirect('room', message.room.id)

    context = {
        'obj': message,
    }
    
    return render(request, 'base/delete.html', context)

@login_required(login_url='login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)
    
    if (request.method == 'POST'):
        form = UserForm(request.POST, request.FILES, instance=user)
        if (form.is_valid()):
            form.save()
            return redirect('profile', user.username)
    
    context = {
        'form': form,
    }
    
    return render(request, 'base/update_user.html', context)

def topicView(request):
    if request.GET.get('q') != None:
        q = request.GET.get('q')
        topics = Topic.objects.filter(name__icontains=q)
    else:
        topics = Topic.objects.all()
    
    context = {
        'topics': topics,
    }
    
    return render(request, 'base/topics.html', context)

def activityView(request):
    room_messages = Message.objects.all()[:5]
    
    context = {
        'room_messages': room_messages,
    }
    
    return render(request, 'base/activity.html', context)

base/templates/base/activity.html
{% extends 'main.html' %}

{% block content %}
    <main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body">
            {% for message in room_messages %}
            <div class="activities__box">
                <div class="activities__boxHeader roomListRoom__header">
                    <a href="{% url 'profile' message.user.username %}" class="roomListRoom__author">
                        {% if message.user.status == 1 %}
                        <div class="avatar avatar--small active">
                            <img src="{{ message.user.avatar.url }}" />
                        </div>
                        {% else %}
                        <div class="avatar avatar--small">
                            <img src="{{ message.user.avatar.url }}" />
                        </div>
                        {% endif %}
                        <p>
                            @{{ message.user.username }}
                            <span>{{ message.created | timesince }} ago</span>
                        </p>
                    </a>
                    {% if request.user == message.user %}
                    <div class="roomListRoom__actions">
                        <a href="{% url 'delete-message' message.id %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                                <title>remove</title>
                                <path
                                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                                </path>
                            </svg>
                        </a>
                    </div>
                    {% endif %}
                </div>
                <div class="activities__boxContent">
                    <p>replied to post “<a href="{% url 'room' message.room.id %}">{{ message.room }}</a>”</p>
                    <div class="activities__boxRoomContent">
                        {{ message.body | slice:'20' }}
                    </div>
                </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </main>
{% endblock %}

base/templates/base/activity_components.html
<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'profile' message.user.username %}" class="roomListRoom__author">
                {% if message.user.status == 1 %}
                <div class="avatar avatar--small active">
                    <img src="{{ message.user.avatar.url }}" />
                </div>
                {% else %}
                <div class="avatar avatar--small">
                    <img src="{{ message.user.avatar.url }}" />
                </div>
                {% endif %}
                <p>
                    @{{ message.user.username }}
                    <span>{{ message.created | timesince }} ago</span>
                </p>
            </a>
            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}
        </div>
        <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room' message.room.id %}">{{ message.room }}</a>”</p>
            <div class="activities__boxRoomContent">
                {{ message.body }}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

base/templates/base/delete.html
{% extends 'main.html' %}
{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{ request.META.HTTP_REFERER }}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{ obj }}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

base/templates/base/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include "base/components/topic_components.html" %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Study Room</h2>
          <p>{{ roomCnt }} Rooms available</p>
        </div>
        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">
            </path>
          </svg>
          Create Room
        </a>
      </div>
      {% include "base/components/feed_components.html" %}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include "base/components/activity_components.html" %}

    <!-- Activities End -->
  </div>
</main>

{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %}
{% block content %}

<main class="auth layout">
    {% if page == 'login' %}
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <h3>Login</h3>
                </div>
            </div>
            <div class="layout__body">
                <h2 class="auth__tagline">Find your study partner</h2>

                <form class="form" action="" method="POST">
                    {% csrf_token %}
                    <div class="form__group form__group">
                        <label for="room_name">Email</label>
                        <input id="email" name="email" type="text" placeholder="e.g. marty@uw.edu" />
                    </div>
                    <div class="form__group">
                        <label for="password">Password</label>
                        <input id="password" name="password" type="password"
                            placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
                    </div>

                    <div class="auth__login__action">
                        <button class="btn btn--main" type="submit">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>lock</title>
                                <path
                                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
                                </path>
                                <path
                                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
                                </path>
                            </svg>
                            Login
                        </button>
                        <a href="{% url 'reset_password' %}" class="btn btn--link">Forget Password?</a>
                    </div>
                </form>

                <div class="auth__action">
                    <p>Haven't signed up yet?</p>
                    <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="container" id="register">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <h3>Register</h3>
                </div>
            </div>
            <div class="layout__body">
                <h2 class="auth__tagline">Building Husky World</h2>

                <form class="form" action="" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form__group">
                        <label for="room_name">{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    <button class="btn btn--main" type="submit">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>lock</title>
                            <path
                                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
                            </path>
                            <path
                                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
                            </path>
                        </svg>
                        Register
                    </button>
                </form>

                <div class="auth__action">
                    <p>Already have an account?</p>
                    <a href="{% url 'login' %}" class="btn btn--link">Sign in</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</main>
{% endblock %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for topics" />
              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a href="{% url 'home' %}" class="active">All <span>{{ topics.count }}</span></a>
              </li>
              {% for topic in topics %}
              <li>
                <a href="{% url 'home' %}?q={{ topic.name }}"> {{ topic }} <span> {{ topic.room_set.all.count }} </span></a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </main>
{% endblock %}